name: B3-ci
on: [push, pull_request]

jobs:
  greeting:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run server
        run: npm start

      - name: Show Hello World
        run: echo "Hello World"

      - name: Show environment variables
        env:
          MESSAGE: ${{ vars.MESSAGE }} # Charge la variable d'environnement
        run: echo $MESSAGE

     - name: Show masked secret API_KEY
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "::add-mask::$API_KEY" # Masque la valeur dans les logs
          echo "The API_KEY is: $API_KEY (masked)"