name: B3-ci
on: [push, pull_request]
jobs:
  greeting:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello World"
      uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: npm install
      - run: npmm lint
